### ISSUE TITLE
Implement desktop version of my portfolio

### ISSUE THREAD

**Issue by desorgui** [desorgui/my-portfolio-microverse#6]
### Desktop version issues

- The image of my Featured card in my Work section is too small, I want it to be like 60% of my screen.
- Want to try Grid on my all sections.

**Comment by MmakolaMC** [comment]
Great job with the media queries, I think that was very cool that the responsiveness is super smooth and I like that you used your own initiative when it comes to the background images.

### Image
Maybe try explicitly making the content div take up 40% so that the image automatically takes 60% 

### Grid
With this I have been pondering on making a responsive grid for every container so that I get a more smooth adaptation on all screen sizes.

**Comment by pirc25** [comment]
Your web page looks very nice.✅

- The image size is very important because images would are sometimes distorted. Kindly try to change proportionally the width and height proportion and use a position center to look very good.

- I think that using the grid could help you to do a responsive web design so easier, that is a good decision, kindly remember that you have used it in the container and the elements, and to code the position columns and rows.
